#!/usr/bin/env python3
"""kudcrafts: the mascot launcher icon, from one geometry.

Writes the adaptive icon (vector foreground + monochrome, teal background colour), legacy PNG mipmaps, the
in-app logo and the white notification silhouette into app/src/fdroid/res, and preview renders (every launcher
mask, the notification icon at 24 dp) into the directory given as argv[1]. Needs Pillow.
Matches web-kc/public/static/images/pwa-512x512.png: teal ground, cream tilted rounded square with a face,
coral dot on its top-right corner.
"""
import math, os, sys
from PIL import Image, ImageDraw, ImageChops

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RES = os.path.join(ROOT, "app/src/fdroid/res")
OUT = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "build/kc-icon")

TEAL, CREAM, CORAL, INK = "#2A9484", "#FEF7E8", "#FD6D5A", "#0C504E"

# Geometry in the 108 dp adaptive-icon viewport. Safe zone = circle r 33 around (54, 54).
SQ = dict(cx=52.0, cy=57.0, side=44.0, r=13.5, rot=-10.0)          # rotation: Android degrees (clockwise +)
DOT = dict(cx=69.5, cy=37.0, r=8.5)
EYES = [(-6.0, 6.5), (11.0, 5.0)]                                  # relative to the square centre, before rotation
EYE_RX, EYE_RY = 2.6, 3.3
SMILE = dict(dx=2.6, dy=10.5, w=7.0, h=3.0, stroke=2.0)

def rot(x, y, cx, cy, deg):
    a = math.radians(deg)
    dx, dy = x - cx, y - cy
    return cx + dx * math.cos(a) - dy * math.sin(a), cy + dx * math.sin(a) + dy * math.cos(a)

def rrect_path(x, y, w, h, r):
    return (f"M{x+r:.2f},{y:.2f} H{x+w-r:.2f} A{r:.2f},{r:.2f} 0 0 1 {x+w:.2f},{y+r:.2f} "
            f"V{y+h-r:.2f} A{r:.2f},{r:.2f} 0 0 1 {x+w-r:.2f},{y+h:.2f} H{x+r:.2f} "
            f"A{r:.2f},{r:.2f} 0 0 1 {x:.2f},{y+h-r:.2f} V{y+r:.2f} A{r:.2f},{r:.2f} 0 0 1 {x+r:.2f},{y:.2f} Z")

def ellipse_path(cx, cy, rx, ry):
    return (f"M{cx-rx:.2f},{cy:.2f} A{rx:.2f},{ry:.2f} 0 1 0 {cx+rx:.2f},{cy:.2f} "
            f"A{rx:.2f},{ry:.2f} 0 1 0 {cx-rx:.2f},{cy:.2f} Z")

def scaled(g, k, ox=0.0, oy=0.0):
    return {key: (v * k + (ox if key == "cx" else oy if key == "cy" else 0) if key in ("cx", "cy") else (v * k if key not in ("rot",) else v)) for key, v in g.items()}

def vector_mascot(size, sq, dot, eyes, eye_rx, eye_ry, smile, colours, mono=False, gap=0.0):
    """VectorDrawable XML. colours = (square, dot, face) or a single colour for silhouettes (face cut out)."""
    x, y = sq["cx"] - sq["side"] / 2, sq["cy"] - sq["side"] / 2
    sq_path = rrect_path(x, y, sq["side"], sq["side"], sq["r"])
    eye_paths = " ".join(ellipse_path(sq["cx"] + ex, sq["cy"] + ey, eye_rx, eye_ry) for ex, ey in eyes)
    sx, sy = sq["cx"] + smile["dx"], sq["cy"] + smile["dy"]
    smile_path = f"M{sx - smile['w']/2:.2f},{sy:.2f} Q{sx:.2f},{sy + smile['h']*2:.2f} {sx + smile['w']/2:.2f},{sy:.2f}"
    dot_path = ellipse_path(dot["cx"], dot["cy"], dot["r"], dot["r"])
    head = (f'<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
            f'    android:width="{size}dp" android:height="{size}dp"\n'
            f'    android:viewportWidth="{size}" android:viewportHeight="{size}">\n')
    group = f'    <group android:rotation="{sq["rot"]}" android:pivotX="{sq["cx"]}" android:pivotY="{sq["cy"]}">\n'
    if mono:
        c = colours
        gr = dot["r"] + gap
        # Clip = whole canvas (clockwise) minus a counter-clockwise circle around the dot: a gap between dot and square
        clip = f"M0,0 H{size} V{size} H0 Z " + ellipse_path(dot["cx"], dot["cy"], gr, gr)
        body = ('    <group>\n'
                f'        <clip-path android:pathData="{clip}"/>\n' +
                group.replace("    <group", "        <group") +
                f'            <path android:fillColor="{c}" android:fillType="evenOdd" android:pathData="{sq_path} {eye_paths}"/>\n'
                '        </group>\n'
                '    </group>\n'
                f'    <path android:fillColor="{c}" android:pathData="{dot_path}"/>\n')
    else:
        csq, cdot, cface = colours
        body = (group +
                f'        <path android:fillColor="{csq}" android:pathData="{sq_path}"/>\n'
                f'        <path android:fillColor="{cface}" android:pathData="{eye_paths}"/>\n'
                f'        <path android:strokeColor="{cface}" android:strokeWidth="{smile["stroke"]}" android:strokeLineCap="round" android:pathData="{smile_path}"/>\n'
                '    </group>\n'
                f'    <path android:fillColor="{cdot}" android:pathData="{dot_path}"/>\n')
    return "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<!-- kudcrafts: generated by scripts/kc-icon.py -->\n" + head + body + "</vector>\n"

# ---------- raster (same geometry) ----------
SS = 8  # supersampling

def draw_mascot(canvas_px, view, sq, dot, eyes, eye_rx, eye_ry, smile, colours, mono=False, bg=None, gap=0.0):
    k = canvas_px * SS / view
    W = canvas_px * SS
    img = Image.new("RGBA", (W, W), bg or (0, 0, 0, 0))
    # Square + face drawn upright on a layer, then rotated about the square centre
    layer = Image.new("RGBA", (W, W), (0, 0, 0, 0))
    d = ImageDraw.Draw(layer)
    x0, y0 = (sq["cx"] - sq["side"] / 2) * k, (sq["cy"] - sq["side"] / 2) * k
    x1, y1 = x0 + sq["side"] * k, y0 + sq["side"] * k
    sqc = colours if mono else colours[0]
    d.rounded_rectangle([x0, y0, x1, y1], radius=sq["r"] * k, fill=sqc)
    face = (0, 0, 0, 0) if mono else colours[2]
    for ex, ey in eyes:
        cx, cy = (sq["cx"] + ex) * k, (sq["cy"] + ey) * k
        d.ellipse([cx - eye_rx * k, cy - eye_ry * k, cx + eye_rx * k, cy + eye_ry * k], fill=face)
    if not mono:
        sx, sy = (sq["cx"] + smile["dx"]) * k, (sq["cy"] + smile["dy"]) * k
        pts = []
        for i in range(41):
            t = i / 40
            px = (1 - t) ** 2 * (sx - smile["w"] / 2 * k) + 2 * (1 - t) * t * sx + t ** 2 * (sx + smile["w"] / 2 * k)
            py = (1 - t) ** 2 * sy + 2 * (1 - t) * t * (sy + smile["h"] * 2 * k) + t ** 2 * sy
            pts.append((px, py))
        d.line(pts, fill=face, width=int(smile["stroke"] * k), joint="curve")
        for p in (pts[0], pts[-1]):
            rr = smile["stroke"] * k / 2
            d.ellipse([p[0] - rr, p[1] - rr, p[0] + rr, p[1] + rr], fill=face)
    layer = layer.rotate(-sq["rot"], resample=Image.BICUBIC, center=(sq["cx"] * k, sq["cy"] * k))
    if mono and gap > 0:
        gr = (dot["r"] + gap) * k
        ImageDraw.Draw(layer).ellipse([dot["cx"] * k - gr, dot["cy"] * k - gr, dot["cx"] * k + gr, dot["cy"] * k + gr], fill=(0, 0, 0, 0))
    img.alpha_composite(layer)
    d = ImageDraw.Draw(img)
    dc = colours if mono else colours[1]
    d.ellipse([(dot["cx"] - dot["r"]) * k, (dot["cy"] - dot["r"]) * k, (dot["cx"] + dot["r"]) * k, (dot["cy"] + dot["r"]) * k], fill=dc)
    return img.resize((canvas_px, canvas_px), Image.LANCZOS)

def mask(shape, px):
    m = Image.new("L", (px * SS, px * SS), 0)
    d = ImageDraw.Draw(m)
    W = px * SS
    if shape == "circle":
        d.ellipse([0, 0, W - 1, W - 1], fill=255)
    elif shape == "rounded-square":
        d.rounded_rectangle([0, 0, W - 1, W - 1], radius=W * 0.16, fill=255)
    elif shape == "squircle":  # superellipse n=4
        pts = []
        for i in range(720):
            t = 2 * math.pi * i / 720
            c, s = math.cos(t), math.sin(t)
            pts.append((W / 2 + W / 2 * math.copysign(abs(c) ** 0.5, c), W / 2 + W / 2 * math.copysign(abs(s) ** 0.5, s)))
        d.polygon(pts, fill=255)
    elif shape == "teardrop":
        d.rounded_rectangle([0, 0, W - 1, W - 1], radius=W * 0.5, fill=255)
        d.rectangle([W / 2, W / 2, W - 1, W - 1], fill=255)
    return m.resize((px, px), Image.LANCZOS)

def launcher_png(px, shape):
    """What a launcher shows: the 108 dp layers scaled so the visible 72 dp fill the icon, then masked."""
    full = int(round(px * 108 / 72))
    layers = draw_mascot(full, 108, SQ, DOT, EYES, EYE_RX, EYE_RY, SMILE, (CREAM, CORAL, INK), bg=TEAL)
    off = (full - px) // 2
    visible = layers.crop((off, off, off + px, off + px))
    out = Image.new("RGBA", (px, px), (0, 0, 0, 0))
    out.paste(visible, (0, 0), mask(shape, px))
    return out

def main():
    os.makedirs(OUT, exist_ok=True)
    for sub in ("drawable", "values", "mipmap-anydpi-v26"):
        os.makedirs(os.path.join(RES, sub), exist_ok=True)

    # Adaptive foreground + monochrome (108 dp)
    open(os.path.join(RES, "drawable/ic_launcher_kc_foreground.xml"), "w").write(
        vector_mascot(108, SQ, DOT, EYES, EYE_RX, EYE_RY, SMILE, (CREAM, CORAL, INK)))
    mono_dot = dict(DOT, r=DOT["r"] - 0.5)
    MONO_GAP = 2.2  # Cut between dot and square so the silhouette keeps the dot readable
    open(os.path.join(RES, "drawable/ic_launcher_kc_monochrome.xml"), "w").write(
        vector_mascot(108, SQ, mono_dot, EYES, EYE_RX + 0.4, EYE_RY + 0.4, SMILE, "#FFFFFFFF", mono=True, gap=MONO_GAP))
    open(os.path.join(RES, "values/kc_icon_colors.xml"), "w").write(
        '<?xml version="1.0" encoding="utf-8"?>\n<!-- kudcrafts: generated by scripts/kc-icon.py -->\n<resources>\n'
        f'    <color name="ic_launcher_kc_background">{TEAL}</color>\n</resources>\n')
    adaptive = ('<?xml version="1.0" encoding="utf-8"?>\n<!-- kudcrafts: generated by scripts/kc-icon.py -->\n'
                '<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n'
                '    <background android:drawable="@color/ic_launcher_kc_background"/>\n'
                '    <foreground android:drawable="@drawable/ic_launcher_kc_foreground"/>\n'
                '    <monochrome android:drawable="@drawable/ic_launcher_kc_monochrome"/>\n'
                '</adaptive-icon>\n')
    for name in ("ic_launcher.xml", "ic_launcher_round.xml"):
        open(os.path.join(RES, "mipmap-anydpi-v26", name), "w").write(adaptive)

    # In-app logo (empty states): the mascot on its own, 48 dp, viewport cropped to the safe zone
    logo_sq = dict(SQ, cx=SQ["cx"] - 21, cy=SQ["cy"] - 21)
    logo_dot = dict(DOT, cx=DOT["cx"] - 21, cy=DOT["cy"] - 21)
    xml = vector_mascot(66, logo_sq, logo_dot, EYES, EYE_RX, EYE_RY, SMILE, (CREAM, CORAL, INK))
    xml = xml.replace('android:width="66dp" android:height="66dp"', 'android:width="64dp" android:height="64dp"')
    # The cream square needs an edge on light backgrounds: a thin teal outline
    xml = xml.replace(f'<path android:fillColor="{CREAM}"', f'<path android:fillColor="{CREAM}" android:strokeColor="{TEAL}" android:strokeWidth="1.5"')
    open(os.path.join(RES, "drawable/ic_sms_gray_48dp.xml"), "w").write(xml)

    # Notification small icon: white silhouette, 24 dp
    k = 21.5 / 54  # the mascot spans ~54 dp of the 108 viewport; the status-bar glyph uses ~21.5 of 24 dp
    ox, oy = 12 - 53.0 * k, 12 - 55.5 * k
    n_sq = dict(cx=SQ["cx"] * k + ox, cy=SQ["cy"] * k + oy, side=SQ["side"] * k, r=SQ["r"] * k, rot=SQ["rot"])
    n_dot = dict(cx=mono_dot["cx"] * k + ox, cy=mono_dot["cy"] * k + oy, r=mono_dot["r"] * k * 1.1)
    n_gap = 1.0  # dp at 24 dp: one physical pixel-ish gap even at mdpi
    n_eyes = [(ex * k, ey * k) for ex, ey in EYES]
    n_smile = dict(SMILE)
    open(os.path.join(RES, "drawable/ic_notification.xml"), "w").write(
        vector_mascot(24, n_sq, n_dot, n_eyes, (EYE_RX + 0.6) * k, (EYE_RY + 0.6) * k, n_smile, "#FFFFFFFF", mono=True, gap=n_gap))

    # Legacy mipmaps (pre-adaptive launchers): rounded square
    for density, px in (("mdpi", 48), ("hdpi", 72), ("xhdpi", 96), ("xxhdpi", 144), ("xxxhdpi", 192)):
        d = os.path.join(RES, f"mipmap-{density}")
        os.makedirs(d, exist_ok=True)
        launcher_png(px, "rounded-square").save(os.path.join(d, "ic_launcher.png"))
        launcher_png(px, "circle").save(os.path.join(d, "ic_launcher_round.png"))

    # ---------- previews ----------
    shapes = ("circle", "squircle", "rounded-square", "teardrop")
    sheet = Image.new("RGBA", (4 * 220 + 20, 2 * 240 + 20), "#E9ECEF")
    for i, shape in enumerate(shapes):
        icon = launcher_png(192, shape)
        icon.save(os.path.join(OUT, f"launcher-{shape}.png"))
        sheet.alpha_composite(icon, (20 + i * 220, 20))
        dark = Image.new("RGBA", (200, 200), "#1C1F22")
        sheet.alpha_composite(dark, (10 + i * 220, 250))
        sheet.alpha_composite(icon, (14 + i * 220, 254))
    sheet.save(os.path.join(OUT, "launcher-masks.png"))

    # Safe-zone check: foreground on a grid with the 66 dp circle drawn
    fg = draw_mascot(432, 108, SQ, DOT, EYES, EYE_RX, EYE_RY, SMILE, (CREAM, CORAL, INK), bg=TEAL)
    d = ImageDraw.Draw(fg)
    d.ellipse([(54 - 33) * 4, (54 - 33) * 4, (54 + 33) * 4, (54 + 33) * 4], outline="#FF00FF", width=2)
    d.rectangle([18 * 4, 18 * 4, 90 * 4, 90 * 4], outline="#FFFF00", width=1)
    fg.save(os.path.join(OUT, "foreground-safe-zone.png"))

    # Themed (monochrome) icon as Android 13 tints it, and the notification icon at real sizes
    mono = draw_mascot(432, 108, SQ, mono_dot, EYES, EYE_RX + 0.4, EYE_RY + 0.4, SMILE, (40, 60, 50, 255), mono=True, bg="#C8E6D8", gap=MONO_GAP)
    m = mask("circle", 288)
    mono_c = mono.crop((72, 72, 360, 360))
    out = Image.new("RGBA", (288, 288), (0, 0, 0, 0))
    out.paste(mono_c, (0, 0), m)
    out.save(os.path.join(OUT, "themed-monochrome.png"))

    bar = Image.new("RGBA", (420, 96), "#202124")
    for i, px in enumerate((24, 36, 48, 72)):
        ni = draw_mascot(px, 24, n_sq, n_dot, n_eyes, (EYE_RX + 0.6) * k, (EYE_RY + 0.6) * k, n_smile, (255, 255, 255, 255), mono=True, gap=n_gap)
        bar.alpha_composite(ni, (12 + sum((24, 36, 48, 72)[:i]) + i * 20, (96 - px) // 2))
    bar.save(os.path.join(OUT, "notification-icon-sizes.png"))
    big = draw_mascot(240, 24, n_sq, n_dot, n_eyes, (EYE_RX + 0.6) * k, (EYE_RY + 0.6) * k, n_smile, (255, 255, 255, 255), mono=True, bg="#202124", gap=n_gap)
    big.save(os.path.join(OUT, "notification-icon-zoom.png"))
    print("wrote", RES, "and previews in", OUT)

if __name__ == "__main__":
    main()
